- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install EPEL
  yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == RedHat

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ init_packages }}"

- name: Configure SSH jail
  template:
    src: template/ssh_jail.conf.j2
    dest: /etc/fail2ban/jail.d/ssh_jail.conf
    owner: root
    group: root
    mode: '644'

- name: Copy global config
  template:
    src: template/global.conf.j2
    dest: /etc/fail2ban/jail.d/global.conf
    owner: root
    group: root
    mode: '644'

- name: Enable fail2ban service
  systemd:
    name: fail2ban
    enabled: yes
    state: started
    masked: no
